### PR TITLE
Add deployment of ff-bot

### PR DESCRIPTION
**Pull request by jb3**
Adds a deployment of https://github.com/jb3/ff_bot which will be used to aid in
fast-forward merges to this repository without having to leave the GitHub Web
UI.

### CODE REVIEW

**Review by shenanigansd — APPROVED** [review]
Winning as usual

**Comment by jb3** [comment]
Ack'd last night, I attempted to use the branch update feature on GitHub hoping it would use the web key to attest to the new commits, but not even that works.

I will re-sign shortly and merge.

**Review by ChrisLovering — APPROVED** [review]

**Comment by jb3** [comment]
I accidentally wiped the change that adds the DNS record by merging something else... give it 15 minutes and someone can try again.

**Pull request merged**
