### PR TITLE
Depend on ansible-core instead of Ansible

### PR DESCRIPTION
**Pull request by jchristgit**
Allow for faster local installation by only installing what we need.

### CODE REVIEW

**Comment by jchristgit** [comment]
Sorry for the updates, this is properly ready for review now.

**Review by shtlrs — CHANGES_REQUESTED** [review]
Looks great ! 

Just one thing left to do due to the changes we've just merged for local testing: the vagrant file will need to be updated to install the custom galaxy collections.

**Comment by jchristgit** [comment]
I updated the `Vagrantfile`. I can't test it locally but I'm relatively convinced it works like this.

**Review by shtlrs — APPROVED** [review]
Tested and works well, thanks !

image

**Pull request merged**
