### PR TITLE
Connect netcup Prometheus to Kubernetes Alertmanager

### LINKED ISSUE #240: Connect Prometheus alerts on netcup to Kubernetes Alertmanager
We want to be able to configure alerts on the Netcup Prometheus instance and
act on it accordingly, with the alerting configuration and HA alertmanager
setup running in Kubernetes.

Joe might be able to give us a token that we can use to talk to Alertmanager in
Kubernetes, and connect our Prometheus instance to it.

### PR DESCRIPTION
**Pull request by jchristgit**
Closes #240.

### CODE REVIEW

**Comment by jb3** [comment]
Does this close #219 as well? As long as alert labels are configured to either `warning` or `page`, this should hit our existing alerting rules.

**Comment by jchristgit** [comment]
No it does not, that ticket is meant for the standalone "I can't reach The Big Alertmanager, please help me" alert

**Comment by jb3** [comment]
Ack, sounds good.

**Review by jb3 — APPROVED** [review]
Looks good, deploy and merge at your convenience.

**Comment by jchristgit** [comment]
At my convenience

**Pull request merged**
